server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


    sentinel:
      transport:
        dashboard: localhost:8080

      web-context-unify: false #controller层的方法对service层调用不认为是同一个跟链路
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow #  com.alibaba.cloud.sentinel.datasource.RuleType




logging:
  level:
    com.atguigu.cloud.Controller.NacosConfigClientController: DEBUG
